version: '3'

services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms4g -Xmx32g"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=7Tr0ngP@ssw0rdwget"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 131072
        hard: 131072
      nproc:
        soft: 4096
        hard: 4096
    volumes:
      - "/home/derf/projects/wiki-search/data/opensearch-data-v7:/usr/share/opensearch/data"
      # - type: volume
      #   source: opensearch-data-v6
      #   target: /usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600

# volumes:
#   opensearch-data-v6:
#     driver: local
#     driver_opts:
#       type: 'none'
#       o: 'bind'
#       device: /home/derf/projects/wiki-search/data/opensearch-data-v6
#       size: 256g


# docker kill $(docker ps -q)
# docker kill $(docker ps -q); docker system prune --volumes --all -f; docker volume prune -f
# docker kill $(docker ps -q); docker volume prune -f

#  docker volume create --driver local --opt o=size=256g,uid=1000 foo
